### PR TITLE
Komitujem Adding1txtfile.txt

### PR DESCRIPTION
**Pull request by x-max**
Ovo je nakon klika na Create pull request iz sourcetree-a 
Opet imam sansu da biram komparaciju izmednju dva repo-a (sad: master <- NewBranch2)
I dugme Create pull request

### CODE REVIEW

**Comment by Millvass** [comment]
Test I ranje

**Review by Millvass — APPROVED** [review]
Vaske is Approving

**Comment by x-max** [comment]
After Vaskez Approved
I decided to merge NewBranch2 to master

**Comment by x-max** [comment]
By mistake I hitted Comment and Close (which closed pull request), but fortunately ther is an option Reopen and comment!

**Pull request merged**
